<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class RestoreExerciseSeeder extends Seeder
{
    public function run()
    {
        // Clear existing
        Schema::disableForeignKeyConstraints();
        DB::table('exercises')->truncate();
        Schema::enableForeignKeyConstraints();

        $exercises = [
            [
                'name' => 'Bench Press',
                'description' => 'A compound exercise targeting the chest, shoulders, and triceps.',
                'body_part' => 'Chest',
                'difficulty' => 'Intermediate',
                'equipment' => '["Barbell","Bench"]',
                'muscle_groups' => '["Pectorals","Triceps","Deltoids"]',
                'instructions' => '["Lie on the bench with your eyes under the bar","Grip the bar slightly wider than shoulder-width","Unrack the bar and lower it to your chest","Press the bar back up to starting position"]',
                'calories_per_hour' => 400,
                'image_url' => 'https://cdn.mos.cms.futurecdn.net/pLaRi5jXSHDKu6WRydetBo-970-80.jpg.webp',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Deadlift',
                'description' => 'A compound exercise that works your entire posterior chain.',
                'body_part' => 'Back',
                'difficulty' => 'Advanced',
                'equipment' => '["Barbell"]',
                'muscle_groups' => '["Hamstrings","Glutes","Back","Core"]',
                'instructions' => '["Stand with feet hip-width apart over the bar","Bend at the hips and grip the bar","Keep your back straight and lift the bar","Return to starting position with control"]',
                'calories_per_hour' => 450,
                'image_url' => 'https://images.unsplash.com/photo-1534367610401-9f5ed68180aa?w=400&h=300&fit=crop&auto=format',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Squat',
                'description' => 'The king of leg exercises, building strength and muscle.',
                'body_part' => 'Legs',
                'difficulty' => 'Intermediate',
                'equipment' => '["Barbell","Squat Rack"]',
                'muscle_groups' => '["Quadriceps","Hamstrings","Glutes","Core"]',
                'instructions' => '["Position the bar on your upper back","Stand with feet shoulder-width apart","Lower your hips down and back","Drive through your heels to stand up"]',
                'calories_per_hour' => 500,
                'image_url' => 'https://cdn.pixabay.com/photo/2019/06/02/04/36/outdoors-4245628_1280.jpg',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Pull-up',
                'description' => 'An upper body compound exercise for back and biceps.',
                'body_part' => 'Back',
                'difficulty' => 'Advanced',
                'equipment' => '["Pull-up Bar"]',
                'muscle_groups' => '["Latissimus Dorsi","Biceps","Core"]',
                'instructions' => '["Hang from the bar with an overhand grip","Pull yourself up until your chin passes the bar","Lower yourself back down with control"]',
                'calories_per_hour' => 350,
                'image_url' => 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=300&fit=crop&auto=format',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Shoulder Press',
                'description' => 'Build strong shoulders and upper body strength.',
                'body_part' => 'Shoulders',
                'difficulty' => 'Intermediate',
                'equipment' => '["Dumbbells","Bench"]',
                'muscle_groups' => '["Deltoids","Triceps","Upper Chest"]',
                'instructions' => '["Sit on a bench with dumbbells at shoulder height","Press the weights overhead","Lower back to starting position with control"]',
                'calories_per_hour' => 350,
                'image_url' => 'https://cdn.mos.cms.futurecdn.net/zrvGQZPFocPaKKgysrcoeK-750-80.jpg.webp',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Plank',
                'description' => 'A core exercise that builds stability and strength.',
                'body_part' => 'Core',
                'difficulty' => 'Beginner',
                'equipment' => '["Bodyweight"]',
                'muscle_groups' => '["Abdominals","Core","Shoulders"]',
                'instructions' => '["Start in a push-up position","Keep your body in a straight line","Hold the position for time"]',
                'calories_per_hour' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1714646442330-9068099f5521?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
                        [
                'name' => 'Dumbbell Curl',
                'description' => 'An isolation exercise targeting the biceps for muscle growth and strength.',
                'body_part' => 'Arms',
                'difficulty' => 'Beginner',
                'equipment' => '["Dumbbells"]',
                'muscle_groups' => '["Biceps","Forearms"]',
                'instructions' => '["Stand with feet shoulder-width apart","Hold dumbbells with palms facing forward","Curl the weights up towards your shoulders","Lower back down with control"]',
                'calories_per_hour' => 250,
                'image_url' => 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop&auto=format',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Triceps Pushdown',
                'description' => 'A cable exercise that isolates and strengthens the triceps muscles.',
                'body_part' => 'Arms',
                'difficulty' => 'Intermediate',
                'equipment' => '["Cable Machine","V-Bar"]',
                'muscle_groups' => '["Triceps","Shoulders"]',
                'instructions' => '["Attach a V-bar to the cable pulley","Grip the bar with palms facing down","Push the bar down until arms are fully extended","Return to starting position with control"]',
                'calories_per_hour' => 280,
                'image_url' => 'https://trainingstation.co.uk/cdn/shop/articles/Tricep-pushdown-movement_ddb8dbd8-566d-4f55-99e0-36c35790234a_1224x.png?v=1739005533',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Lat Pulldown',
                'description' => 'A back exercise that builds width and strength in the latissimus dorsi.',
                'body_part' => 'Back',
                'difficulty' => 'Intermediate',
                'equipment' => '["Cable Machine","Lat Bar"]',
                'muscle_groups' => '["Latissimus Dorsi","Biceps","Rhomboids"]',
                'instructions' => '["Sit at the lat pulldown machine","Grip the bar with palms facing forward","Pull the bar down to your chest","Slowly return to starting position"]',
                'calories_per_hour' => 320,
                'image_url' => 'https://training.fit/wp-content/uploads/2020/02/latzug-enger-griff.png',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Lunges',
                'description' => 'A unilateral leg exercise that builds strength, balance, and stability.',
                'body_part' => 'Legs',
                'difficulty' => 'Beginner',
                'equipment' => '["Bodyweight","Dumbbells"]',
                'muscle_groups' => '["Quadriceps","Hamstrings","Glutes","Core"]',
                'instructions' => '["Stand with feet hip-width apart","Step forward with one leg","Lower your hips until both knees are bent at 90 degrees","Push back to starting position and repeat with other leg"]',
                'calories_per_hour' => 380,
                'image_url' => 'https://cdn.shopify.com/s/files/1/0393/3546/0995/files/Lunge-Blog.jpg',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chest Fly',
                'description' => 'An isolation exercise that targets the inner and outer chest muscles.',
                'body_part' => 'Chest',
                'difficulty' => 'Intermediate',
                'equipment' => '["Dumbbells","Bench"]',
                'muscle_groups' => '["Pectorals","Deltoids"]',
                'instructions' => '["Lie on a flat bench with dumbbells","Extend arms straight up over chest","Lower dumbbells out to the sides in a wide arc","Bring them back together at the top"]',
                'calories_per_hour' => 320,
                'image_url' => 'https://www.shape.com/thmb/4M1ULf7iPf7ioWs2tOEXpU9-tYA=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/SHP_MTM_090922_ChestFly-2000-f259bd1fd90842afa2f4f24bfe31eb5f.jpg',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Russian Twist',
                'description' => 'A rotational core exercise that targets the obliques and improves stability.',
                'body_part' => 'Core',
                'difficulty' => 'Beginner',
                'equipment' => '["Bodyweight","Weight Plate"]',
                'muscle_groups' => '["Obliques","Abdominals","Core"]',
                'instructions' => '["Sit on the floor with knees bent","Lean back slightly keeping your back straight","Twist your torso to the right, then to the left","Keep the movement controlled and steady"]',
                'calories_per_hour' => 280,
                'image_url' => 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-2159279524-68507f004ee1d.jpg',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Kettlebell Swing',
                'description' => 'A dynamic full-body exercise that builds power and cardiovascular fitness.',
                'body_part' => 'Full Body',
                'difficulty' => 'Intermediate',
                'equipment' => '["Kettlebell"]',
                'muscle_groups' => '["Glutes","Hamstrings","Core","Shoulders","Back"]',
                'instructions' => '["Stand with feet shoulder-width apart","Hold the kettlebell with both hands","Swing it between your legs","Explosively swing it up to chest height"]',
                'calories_per_hour' => 500,
                'image_url' => 'https://www.cavemantraining.com/wp-content/uploads/2016/11/breaking-at-the-hips-hip-hinge-delay-kettlebell-swing.jpg',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Face Pull',
                'description' => 'A shoulder health exercise that strengthens the rear delts and rotator cuff.',
                'body_part' => 'Shoulders',
                'difficulty' => 'Intermediate',
                'equipment' => '["Cable Machine","Rope Attachment"]',
                'muscle_groups' => '["Rear Deltoids","Rotator Cuff","Rhomboids","Traps"]',
                'instructions' => '["Set cable at face height","Grip the rope with palms facing each other","Pull the rope towards your face","Pause and squeeze your shoulder blades together"]',
                'calories_per_hour' => 250,
                'image_url' => 'https://www.puregym.com/media/lvvjj3af/face-pulls.jpg?quality=80',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Leg Press',
                'description' => 'A machine-based compound exercise for building leg strength and muscle mass.',
                'body_part' => 'Legs',
                'difficulty' => 'Beginner',
                'equipment' => '["Leg Press Machine"]',
                'muscle_groups' => '["Quadriceps","Hamstrings","Glutes","Calves"]',
                'instructions' => '["Sit on the leg press machine","Place feet on the platform shoulder-width apart","Press the platform away by extending your legs","Slowly return to starting position"]',
                'calories_per_hour' => 350,
                'image_url' => 'https://bellsofsteel.au/cdn/shop/articles/Leg-Pressing-101_-How-Much-Should-I-Leg-Press.webp?v=1717080632&width=1000',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mountain Climbers',
                'description' => 'A high-intensity bodyweight cardio exercise that builds endurance and core strength.',
                'body_part' => 'Full Body',
                'difficulty' => 'Advanced',
                'equipment' => '["Bodyweight"]',
                'muscle_groups' => '["Core","Shoulders","Hip Flexors","Cardio"]',
                'instructions' => '["Start in a high plank position","Drive one knee towards your chest","Quickly switch legs, alternating back and forth","Maintain a fast pace and keep your hips low"]',
                'calories_per_hour' => 550,
                'image_url' => 'https://images.ctfassets.net/hjcv6wdwxsdz/1WCM5ZFQUTUvuDohwMqr3B/f9b0d7e0eefafd21806937e72b2f867e/mountain-climbers.png?w=800&h=588&q=90&fm=avif',
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        foreach ($exercises as $exercise) {
            DB::table('exercises')->insert($exercise);
        }

        $this->command->info('✅ Exercises restored successfully!');
        $this->command->info('📊 Total exercises: ' . DB::table('exercises')->count());
    }
}